stages:
- stage: Print
  jobs:
  - job: A
    pool:
     vmImage: 'ubuntu-16.04'
    steps:
    - bash: echo "A"
- stage: Verify Release State
  jobs:
  - job: A
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'QA-1 Get Latest Release Bom ID'
        method: 'GET'
        headers: |
          {
          "Content-Type":"application/json", 
          "Accept":"application/json"
          }
        waitForCompletion: 'false'
        successCriteria: 'eq(root[''releaseState''], ''closed'')'