stages:
- stage: Initiate_Deployment
  jobs:
  - job: Commit
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'QA-1 Commit'
        method: 'POST'
        headers: |
          {
          "Content-Type":"application/json", 
          "Accept":"application/json"
        waitForCompletion: 'false'
  - job: Verify_Release_State
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'QA-1 Get Latest Release Bom ID'
        method: 'GET'
        headers: |
          {
          "Content-Type":"application/json", 
          "Accept":"application/json"
          }
        waitForCompletion: 'false'
        successCriteria: 'eq(root[''releaseState''], ''open'')'
  - job: Deploy
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'QA-1 Trigger Deployment'
        method: 'POST'
        headers: |
          {
          "Content-Type":"application/json", 
          "Accept":"application/json"
          }
        body: |
          {
              "cms_deployment": {
                  "releaseId": "",
                  "nsPath": "/ProductDemo/Java/qa-1/bom"
              }
          }
        waitForCompletion: 'false'
  - job: Delay
    pool: server
    steps:
    - task: Delay@1
      inputs:
        delayForMinutes: '1'
- stage: Verify_Status
  jobs:
  - job: Status
    pool: server
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          curl -i -u FLyHmy44t8qnHckeenzx: -H "Content-Type:application/json" -H "Accept:application/json" -X GET -v http://182.76.197.43:3000/ProductDemo/assemblies/Java/transition/environments/prod/releases/bom -o /tmp/deploymentid.json
          deploymentid=$(echo $(grep -oP '"deploymentId"\s*:\s*\K\d+' /tmp/deploymentid.json))
          echo "##vso[task.setvariable variable=deploymentid;]$deploymentid"
  - job: Status
    pool: server
    steps:
    