stages:
- stage: commit
  jobs:
  - job: Commit
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'QA-1 Commit'
        method: 'POST'
        headers: |
          {
          "Content-Type":"application/json", 
          "Accept":"application/json"
        waitForCompletion: 'false'
  - job: Verify_Release_State
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'QA-1 Get Latest Release Bom ID'
        method: 'GET'
        headers: |
          {
          "Content-Type":"application/json", 
          "Accept":"application/json"
          }
        waitForCompletion: 'false'
        successCriteria: 'eq(root[''releaseState''], ''disabled'')'