stages:
- stage: A
  jobs:
  - job: A
    pool:
     vmImage: 'ubuntu-16.04'
    steps:
    - bash: echo "A"
- stage: B
  jobs:
  - job: A
    pool:
     vmImage: 'ubuntu-16.04'
    steps:
    - bash: echo "B"