stages:
- stage: Initiate_Deployment
  jobs:
  - job: Commit
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'QA-1 Commit'
        method: 'POST'
        headers: |
          {
          "Content-Type":"application/json", 
          "Accept":"application/json"
        waitForCompletion: 'false'
  - job: Verify_Release_State
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'QA-1 Get Latest Release Bom ID'
        method: 'GET'
        headers: |
          {
          "Content-Type":"application/json", 
          "Accept":"application/json"
          }
        waitForCompletion: 'false'
        successCriteria: 'eq(root[''releaseState''], ''open'')'
  - job: Deploy
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'QA-1 Trigger Deployment'
        method: 'POST'
        headers: |
          {
          "Content-Type":"application/json", 
          "Accept":"application/json"
          }
        body: |
          {
              "cms_deployment": {
                  "releaseId": "",
                  "nsPath": "/ProductDemo/Java/qa-1/bom"
              }
          }
        waitForCompletion: 'false'
  - job: Delay
    pool: server
    steps:
    - task: Delay@1
      inputs:
        delayForMinutes: '1'
- stage: Verify Status
  jobs:
  - job: Status
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'status'
        method: 'GET'
        headers: |
          {
          "Content-Type":"application/json", 
          "Accept":"application/json"
          }
        urlSuffix: '194351/status'
        waitForCompletion: 'false'